### ISSUE TITLE
Event handling example

### ISSUE THREAD

**Issue by achardon** [learn-co-curriculum/react-hooks-class-events#1]
In the last example of this lesson (right before the conclusion), it says if you bind the event handler to 'this', then you will still have access to 'this' in that event handler. However, when 'this.props' is console-logged, it logs 'undefined'. Is that supposed to happen? Shouldn't it console log the props?

**Comment by ihollander** [comment]
@achardon good catch! The syntax is a bit off in that last example. I'll make an update to the readme.

**Comment by achardon** [comment]
Great, thanks!
